---
title: "Fig2"
author: "Douglas Fritz"
date: "2025-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Plot specific lineages separately

```{r}
for (i in 1:4) {
  # Retrieve relevant variables
  split <- get(paste0('split_', i))
  res_fitness <- get(paste0('res_fitness_', i))
  name_groups <- get(paste0('name_groups_', i))
  colors_groups <- get(paste0('colors_groups_', i))
  
  # Order colors dynamically
  order_colors <- order(as.numeric(split$tip_and_nodes_groups))
  assign(paste0('order_colors_', i), order_colors)
  
  # Assign lineage colors dynamically
  colour_lineage <- colors_groups[match(split$tip_and_nodes_groups[order_colors], name_groups)]
  assign(paste0('colour_lineage_', i), colour_lineage)
  
  png(filename = glue("3_Output_Figures/3_5_DENV/3_5_2_Figure 2/Fitness_Lineage_%02d_plot_DENV_{i}_{st}_min_year_{min_year_model}.png"), width = 1600, height = 1400, res = 300)
  
  # Plot fitness data
  plot_fit_data_per_group(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage
  )
  
  # Add legend
  legend(
    'topright', 
    legend = name_groups,
    fill = colour_lineage, 
    border = colour_lineage,
    cex = 0.5, bty = 'n', ncol = 5
  )
  
  # Close the PNG device
  dev.off()
}
```

Plot lineages seperantely on 1 plot
```{r lineage plot combined}
for (i in 1:4) {
  split         <- get(paste0('split_', i))
  res_fitness   <- get(paste0('res_fitness_', i))
  name_groups   <- get(paste0('name_groups_', i))
  colors_groups <- get(paste0('colors_groups_', i))

  order_colors   <- order(as.numeric(split$tip_and_nodes_groups))
  colour_lineage <- colors_groups[match(split$tip_and_nodes_groups[order_colors], name_groups)]

  K    <- res_fitness$data$K
  cols <- 3L
  rows <- ceiling(K / cols)

  # Each panel = 5in wide x 3in high @ 300 dpi
  w_in <- cols * 5
  h_in <- rows * 3

  # Open a device sized by the grid (units in inches = super convenient)
  png(
    filename = glue("3_Output_Figures/3_5_DENV/3_5_2_Figure 2/Fitness_Lineage_All_plot_DENV_{i}_{st}_min_year_{min_year_model}.png"),
    width = w_in, height = h_in, units = "in", res = 300, type = "cairo-png"
  )

  op <- par(no.readonly = TRUE)
  # Tighter margins so many small panels won’t hit "figure margins too large"
  par(
    mfrow = c(rows, cols),
    mar = c(2, 2, 1.2, 1.0),
    oma = c(0, 0, 0, 0),
    mgp = c(1.2, 0.4, 0),
    tcl = -0.25,
    xaxs = "i", yaxs = "i",
    cex = 0.9
  )

  # Draw all K panels (the function plots one panel per lineage internally)
  tryCatch({
    plot_fit_data_per_group(
      data   = res_fitness$data,
      Chains = res_fitness$chains,
      colour_lineage = colour_lineage
    )

    # Legend on the last panel (kept simple). If you prefer a global legend,
    # we can allocate an extra panel or use outer margins.
    legend(
      "topright", legend = name_groups,
      fill = colour_lineage, border = colour_lineage,
      cex = 0.6, bty = "n", ncol = 5
    )
  }, finally = {
    par(op); dev.off()
  })
}
```





Plot the predicted vs observed proportions:

```{r observed vs predicted single, eval=FALSE}
plot_observed_vs_predicted(data = res_fitness$data,
                           Chains = res_fitness$chains,
                           colour_lineage = colour_lineage)

```

```{r observed vs predicted dynamic loop}
for (i in 1:4) {
  res_fitness <- get(paste0('res_fitness_', i))
  colour_lineage <- get(paste0('colour_lineage_', i))
  png(filename = glue("3_Output_Figures/3_5_DENV/3_5_2_Figure 2/Observed_vs_predicted_DENV_{i}_{st}_min_year_{min_year_model}.png")
      , width = 1600, height = 1400, res = 300)

  plot_observed_vs_predicted(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage
  )
  
  dev.off()
}

## For best year model
for (i in 1:4) {

  # Retrieve plotting variables
  serotype_name <- paste0("DENV", i)
  best_year <- get(paste0('best_year_', i))
  res_fit <- get(paste0('res_fitness_best_year_', i))
  colour_lineage <- get(paste0('colour_lineage_', i))
  
  png(filename = paste0("3_Output_Figures/observed_vs_predicted_DENV_", i, "min_year_", min_year, "_bp_", best_year, "_" ,st, ".png"), width = 1600, height = 1400, res = 300)

  plot_observed_vs_predicted(
    data = res_fit$data,
    Chains = res_fit$chains,
    colour_lineage = colour_lineage
  )
  
  dev.off()
  
}

```

Plot raw fitness estimates:

```{r relative fitness dynamic loop}
for (i in 1:4) {
  res_fitness <- get(paste0('res_fitness_', i))
  colour_lineage <- get(paste0('colour_lineage_', i))
  # Save the plot as a PNG
  png(filename = paste0("3_Output_Figures/estimated_fitness_ref_ancestral_DENV_", i, "min_year_", min_year, "_", st, ".png"), width = 1600, height = 1200, res = 300)
  
  # Plot estimated fitness relative to ancestral reference
  plot_estimated_fitness_ref_ancestral(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage,
    gentime = 1
  )
  

  dev.off()
}




#Best Yyear 
for (i in 1:4) {
  res_fitness <- get(paste0('res_fitness_best_year_', i))
  colour_lineage <- get(paste0('colour_lineage_', i))
  best_year <- get(paste0('best_year_', i))
  # Save the plot as a PNG
  png(filename = paste0("3_Output_Figures/estimated_fitness_ref_ancestral_DENV_", i, "min_year_", min_year, "_bp_", best_year, "_" , st, ".png"), width = 1600, height = 1200, res = 300)
  
  # Plot estimated fitness relative to ancestral reference
  plot_estimated_fitness_ref_ancestral_breakpoint(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage,
    gentime = 1 # Gentime is set to 1 year 
  )
  

  dev.off()
}



plot_estimated_fitness_ref_ancestral(
    data = res_fitness_3$data,
    Chains = res_fitness_3$chains,
    colour_lineage = colour_lineage_3,
    gentime = 1
  )

plot_estimated_fitness_ref_ancestral_breakpoint(
    data = res_fitness_best_year_3$data,
    Chains = res_fitness_best_year_3$chains,
    colour_lineage = colour_lineage_3,
    gentime = 1
  )

## TODO: Ask noemie why gentime is 1 rather than actually generation time and why the ancestral strain set to 0 does not correspond with the most ancestral linage

```

Alternatively you may wish to plot the model, observed vs predicted and
relative fitness graphs together

```{r three panel fitness plots }

for (i in 1:4) {

## ------ Model Plot ------ ##

# Retrieve relevant variables
  split <- get(paste0('split_', i))
  res_fitness <- get(paste0('res_fitness_', i))
  name_groups <- get(paste0('name_groups_', i))
  colors_groups <- get(paste0('colors_groups_', i))
  
  # Order colors dynamically
  order_colors <- order(as.numeric(split$tip_and_nodes_groups))
  assign(paste0('order_colors_', i), order_colors)
  
  # Assign lineage colors dynamically
  colour_lineage <- colors_groups[match(split$tip_and_nodes_groups[order_colors], name_groups)]
  assign(paste0('colour_lineage_', i), colour_lineage)
  
  svglite(filename = paste0("3_Output_Figures/threepanel_fitness_plot_DENV_", i, "_", st, ".svg"), width = 3.33)
  
  par(mfrow = c(3, 1), oma = (c(1,1,2,1)+0.1), mar=(c(4,4,1,1)+ 0.1)) #c(bottom, left, top, right)
  
  # Plot fitness data
  
  plot_fit_data_new(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage,
    xmin = min_year, 
    xmax = max_year
  )
  
  # Add legend
  legend(
    'topright', 
    legend = name_groups,
    fill = colour_lineage, 
    border = colour_lineage,
    cex = 0.5, bty = 'n', ncol = 5
  )
  
## ------ Obs vs predicted Plot ------ ##
  plot_observed_vs_predicted(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage
  )

## ------ Relative Fitness Plot ------ ##
  # Plot estimated fitness relative to ancestral reference
  plot_estimated_fitness_ref_ancestral(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage,
    gentime = 1
  )
  
  mtext(paste0("DENV", i), line=0, side=3, outer=TRUE, cex=1)
  
  dev.off()
 
} 



# Breakpoint
for (i in 1:4) {

## ------ Model Plot ------ ##

# Retrieve relevant variables
  split <- get(paste0('split_', i))
  res_fitness <- get(paste0('res_fitness_best_year_', i))
  name_groups <- get(paste0('name_groups_', i))
  colors_groups <- get(paste0('colors_groups_', i))
  best_year <- get(paste0('best_year_', i))
  
  # Order colors dynamically
  order_colors <- order(as.numeric(split$tip_and_nodes_groups))
  assign(paste0('order_colors_', i), order_colors)
  
  # Assign lineage colors dynamically
  colour_lineage <- colors_groups[match(split$tip_and_nodes_groups[order_colors], name_groups)]
  assign(paste0('colour_lineage_', i), colour_lineage)
  
  svglite(filename = paste0("3_Output_Figures/threepanel_fitness_plot_DENV_", i, "bp_", best_year,"_" , st, ".svg"), width = 3.33)
  
  par(mfrow = c(3, 1), oma = (c(1,1,2,1)+0.1), mar=(c(4,4,1,1)+ 0.1)) #c(bottom, left, top, right)
  
  # Plot fitness data
  
  plot_fit_data_new(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage,
    xmin = min_year, 
    xmax = max_year
  )
  
  # Add legend
  legend(
    'topright', 
    legend = name_groups,
    fill = colour_lineage, 
    border = colour_lineage,
    cex = 0.5, bty = 'n', ncol = 5
  )
  
## ------ Obs vs predicted Plot ------ ##
  plot_observed_vs_predicted(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage
  )

## ------ Relative Fitness Plot ------ ##
  # Plot estimated fitness relative to ancestral reference
  plot_estimated_fitness_ref_ancestral_breakpoint(
    data = res_fitness$data,
    Chains = res_fitness$chains,
    colour_lineage = colour_lineage,
    gentime = 1
  )
  
  mtext(paste0("DENV", i), line=0, side=3, outer=TRUE, cex=1)
  
  dev.off()
 
} 
  
  
```
